name: ci-workflow-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest

    services:
        postgres:
          image: postgres:13.1-alpine
          env:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: bank
          # Set health checks to wait until postgres has started
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - name: Run Migrations
    run: make migrateup
    
    - name: Test
    run: make test
